### ISSUE TITLE
Cannot find module 'kind-of'

### ISSUE THREAD

**Issue by wenshan** [jonschlinkert/merge-deep#4] opened 2016-11-29 12:02 UTC
Cannot find module 'kind-of'

**Comment by doowb** [comment] 2016-11-29 14:51
Please be more specific. Show some code to reproduce the error and the error stack.

Also, make sure to clear the npm cache and reinstall since this is usually the issue:

```sh
# delete node_modules folder
$ rm -fr node_modules
# clear npm cache
$ npm cache clear
# install `merge-deep`
$ npm install merge-deep
```

**Comment by jonschlinkert** [comment] 2016-11-29 23:42
yeah this is definitely a caching issue. just delete `node_modules` and reinstall everything. closing since the issue is [not related to this project](https://github.com/jonschlinkert/merge-deep/blob/master/package.json#L26)

**Closed as completed by jonschlinkert** 2016-11-29 23:42 UTC

**Comment by ulken** [comment] 2020-10-20 06:42
Still get hit by this. Coming from a clean install. I've cleared all caches, removed `node_modules` and re-installed everything. Multiple times.

Don't have time to look into this right now, but if I were to guess, I think it could have something to do with either different versions of `kind-of` being depended upon (I already had version `6.x` installed and this package depends upon `3.x`) or some incompatibility with CommonJS/ESM modules.

For the time being, I've resorted to use another library. A shame, cause I liked how minimal this was.

**Comment by ulken** [comment] 2020-10-20 06:49
If the assumption above is correct, merging #13 and #14 might do the trick.

**Comment by isneezy** [comment] 2020-11-27 16:39
Removing nodemodules didn't solve the problem.

**Comment by kumavis** [comment] 2021-01-27 15:20
Also encountered this problem with fresh `node_modules`

bundling with webpack against `merge-deep@3.0.2` 

cc @jonschlinkert

**Comment by doowb** [comment] 2021-01-27 15:39
> bundling with webpack

This is the first time anyone mentioned `webpack`...

However, no one has provided any more information (e.g. the code using `merge-deep`, their bundler config, an error stack trace, etc...)

**Comment by fingerartur** [comment] 2021-08-20 12:43
I ran into this problem with create-react-app + yarn workspaces + typescript (TS config: "esModuleInterop": true,    "allowSyntheticDefaultImports": true)

I tried importing like this
```
import merge from 'merge-deep'
// and also
const merge = require('merge-deep')
```

... on the other hand when I used it in node.js + typescript and imprted like so
```
const merge = require('merge-deep')
```
it worked fine
